Gustav
leQwang/Web-Programming-Project pull request #2
Opened 2023-05-03 10:08 UTC by GustavElbroend

Here is my code for the login and registration pages.

2023-05-05 04:59 UTC, dev-damien commented on StaticWeb/Login/login.html
> +    <link rel="stylesheet" type="text/css" href="/Web-Programming-Project/StaticWeb/Register/styleRegistration.css">
Shows me an error in chrome, because it cant find the resource. You should use "../" to navigate one folder above and then to the correct file. starting with / results in a lot of problems when it comes to github-pages (learned that in the last assessment :/ )
This is a consequence of our generell project structure (html in subfolders, not at root level)

2023-05-05 05:15 UTC, dev-damien requested changes

2023-05-05 05:15 UTC, dev-damien commented on StaticWeb/Register/registerCustomer.html
> +                            <label for="name" required minlength="5">&#8505;&#65039; Name:
both attributes belong to the input field below

2023-05-05 05:15 UTC, dev-damien commented on StaticWeb/Login/login.html
> +    <link rel="stylesheet" type="text/css" href="/Web-Programming-Project/StaticWeb/Register/styleRegistration.css">
Shows me an error in chrome, because it cant find the resource. You should use "../" to navigate one folder above and then to the correct file. starting with / results in a lot of problems when it comes to github-pages (learned that in the last assessment :/ )
This is a consequence of our generell project structure (html in subfolders, not at root level)

2023-05-05 05:15 UTC, dev-damien commented on StaticWeb/Login/login.html
> +                <button><a href="/Web-Programming-Project/StaticWeb/Register/registerVendor.html">Vendor</a></button>
a inside button or vice versa technically not allowed. you should just remove the button and add something like a "btn-class" to all the a elements to style them like a button
(for all 3 buttons here)

2023-05-05 05:15 UTC, dev-damien commented on StaticWeb/Register/registerVendor.html
> +                            <label for="business-name" required minlength="5">&#8505;&#65039; Business-Name:
attributes belong to input tag, not label

2023-05-06 03:36 UTC, GustavElbroend commented on StaticWeb/Login/login.html
> +    <link rel="stylesheet" type="text/css" href="/Web-Programming-Project/StaticWeb/Register/styleRegistration.css">
Should be resolved now, but please check if the error still occurs after my next pull request.

2023-05-08 09:28 UTC, merged